spring:
  datasource:
    username: twinfniiqfvqfo
    password: ea464217655693eb9bb3de0e2236a6f3014f88d4b1b783afe165b1f4c9cd635f
    url: jdbc:postgresql://ec2-52-19-164-214.eu-west-1.compute.amazonaws.com:5432/dd94uec3k6u7u6
    driver-class-name: org.postgresql.Driver
    hikari:
      maximum-pool-size: 5
  jpa:
    properties:
      hibernate:
        # The SQL dialect makes Hibernate generate better SQL for the chosen database
        dialect: org.hibernate.dialect.PostgreSQLDialect
        jdbc:
          time_zone: UTC
    show-sql: false # Set true for debugging
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    hibernate:
      ddl-auto: update # (create, create-drop, validate, update)
    open-in-view: false
  sql:
    init:
      platform: postgres
      mode: always